export default {
  login: 'banban-22',
  id: 70474028,
  node_id: 'MDQ6VXNlcjcwNDc0MDI4',
  avatar_url: 'https://avatars.githubusercontent.com/u/70474028?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/banban-22',
  html_url: 'https://github.com/banban-22',
  followers_url: 'https://api.github.com/users/banban-22/followers',
  following_url:
    'https://api.github.com/users/banban-22/following{/other_user}',
  gists_url: 'https://api.github.com/users/banban-22/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/banban-22/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/banban-22/subscriptions',
  organizations_url: 'https://api.github.com/users/banban-22/orgs',
  repos_url: 'https://api.github.com/users/banban-22/repos',
  events_url: 'https://api.github.com/users/banban-22/events{/privacy}',
  received_events_url: 'https://api.github.com/users/banban-22/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ayaka Bando',
  company: null,
  blog: 'https://ayakabando.netlify.app/',
  location: 'Vancouver, Canada',
  email: null,
  hireable: null,
  bio: "I'm a Japanese frontend engineer who is very passionate to create web apps using JavaScript and React.js.",
  twitter_username: 'banaya53662508',
  public_repos: 88,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2020-08-30T12:19:02Z',
  updated_at: '2022-09-01T04:37:28Z',
};
